In [2]:
import numpy as np

In [19]:
# array de 1 a 4

arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(arr1+1)
print(2**arr1)

[1 2 3 4]
[2 3 4 5]
[ 2  4  8 16]


In [20]:
# 10 valores entre 0 e 1

arr2 = np.linspace(0, 1, 10)
print(arr2)
print(arr2+1)
print(2**arr2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
[1.         1.08005974 1.16652904 1.25992105 1.36079    1.46973449
 1.58740105 1.71448797 1.85174942 2.        ]


In [24]:
# array 3x3 boolean com todos valores true

# convencional
arrb = np.array([[True for i in range(3)] for i in range(3)])


# jeito numpy
arrb2 = np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
# extrair numeros impares
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr[arr % 2 != 0]

array([1, 3, 5, 7])