In [3]:
import tensorflow as tf


In [4]:
a = tf.constant([9, 8, 7], name = 'a')
b = tf.constant([1, 2, 3], name = 'b')

In [5]:
soma = a + b

In [6]:
type(a)

tensorflow.python.framework.ops.Tensor

In [7]:
print(a)

Tensor("a:0", shape=(3,), dtype=int32)


In [8]:
with tf.Session() as sess:
    print(sess.run(soma))

[10 10 10]


In [9]:
a1 = tf.constant([[1,2,3], [4,5,6]], name = 'a1')

In [10]:
type(a1)

tensorflow.python.framework.ops.Tensor

In [11]:
print(a1)

Tensor("a1:0", shape=(2, 3), dtype=int32)


In [15]:
tam = a1.shape


TensorShape([Dimension(2), Dimension(3)])

In [17]:
b1 = tf.constant([[1,2,3], [4,5,6]], name = 'b1')

In [18]:
soma1 = tf.add(a1, b1)

In [20]:
with tf.Session() as sess:
    print(sess.run(a1))
    print('\n')
    print(sess.run(b1))
    print('\n')
    print(sess.run(soma1))

[[1 2 3]
 [4 5 6]]


[[1 2 3]
 [4 5 6]]


[[ 2  4  6]
 [ 8 10 12]]


In [21]:
a2 = tf.constant([[1,2,3], [4,5,6]])
b2 = tf.constant([[1], [2]])

In [22]:
with tf.Session() as sess:
    print(sess.run(a2))
    print('\n')
    print(sess.run(b2))
    print('\n')

[[1 2 3]
 [4 5 6]]


[[1]
 [2]]


