In [1]:
import numpy as np


In [2]:
minha_lista = [1,2,3]

In [4]:
np.array(minha_lista)
type(np.array(minha_lista))

numpy.ndarray

In [5]:
minha_matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 10)


array([0])

In [9]:
np.arange(0, 10, 3)


array([0, 3, 6, 9])

In [10]:
np.zeros(3,3)

TypeError: data type not understood

In [11]:
arr = np.zeros(3)

In [12]:
arr = np.zeros((5,5))

In [13]:
arr


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
arr = np.zeros((100,100))

In [15]:
arr


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

matriz identidade

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [23]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [25]:
np.random.rand(5)

array([0.0246309 , 0.4031431 , 0.98842072, 0.67367583, 0.67334762])

In [26]:
np.random.rand(5) * 100


array([60.07824936, 91.61528608, 69.70124506, 86.95482941,  2.1376491 ])

In [27]:
np.random.rand(5, 4)

array([[0.90900865, 0.16831112, 0.66593191, 0.96450588],
       [0.26167578, 0.3196555 , 0.83290514, 0.91002837],
       [0.53229295, 0.61366412, 0.60921398, 0.77350024],
       [0.44261144, 0.97945867, 0.59449605, 0.09496701],
       [0.55577101, 0.12880324, 0.36188125, 0.03384901]])

In [30]:
np.random.rand(5, 5, 3)

array([[[8.65786793e-01, 5.36338398e-01, 4.04581023e-02],
        [3.74063426e-01, 5.37108726e-02, 7.37134578e-01],
        [4.62312648e-01, 7.76121585e-01, 9.28577898e-01],
        [2.01042007e-01, 7.33551951e-01, 1.93080143e-01],
        [7.48620694e-04, 1.68692819e-01, 2.36896923e-01]],

       [[9.37003073e-02, 7.69451792e-01, 2.30427573e-01],
        [4.02581377e-01, 1.00386472e-01, 5.90320753e-01],
        [9.36378400e-02, 6.14690538e-01, 9.46047934e-01],
        [7.05932806e-02, 8.19672496e-01, 4.69722979e-01],
        [5.15950927e-01, 1.17271388e-01, 2.29260978e-01]],

       [[4.35327368e-01, 2.24371278e-01, 4.00545626e-02],
        [7.50518985e-01, 9.08893123e-01, 6.69095807e-02],
        [5.49379157e-01, 3.67504766e-01, 1.51251240e-01],
        [5.10784074e-01, 1.51652631e-01, 9.52303675e-01],
        [6.79335218e-01, 4.08986482e-01, 9.81456867e-01]],

       [[8.26031032e-01, 2.40519233e-01, 8.50552161e-01],
        [7.86586907e-02, 7.39957495e-01, 2.51412039e-02],
        

In [31]:
np.random.randn(5)

array([-0.64593431, -0.44791004,  1.03437021, -0.58593447, -0.02396598])

In [32]:
np.random.randint(5)

1

In [33]:
np.random.randint(0, 100, 10)

array([40, 10, 36, 51, 20, 40, 19, 48, 10, 48])

In [35]:
np.round(np.random.rand(5)*100, 0)

array([ 8., 27., 16., 17., 57.])

In [36]:
arr = np.random.rand(25)

In [37]:
arr

array([0.88142763, 0.13055543, 0.21486116, 0.22138729, 0.69008903,
       0.9662225 , 0.73637454, 0.14949959, 0.10657989, 0.15678029,
       0.65475878, 0.61112632, 0.15130359, 0.38630224, 0.59134643,
       0.02365568, 0.71765256, 0.71027491, 0.46577372, 0.33993732,
       0.69644506, 0.98375941, 0.74706062, 0.96758019, 0.59446233])

In [38]:
arr.reshape((5,5))

array([[0.88142763, 0.13055543, 0.21486116, 0.22138729, 0.69008903],
       [0.9662225 , 0.73637454, 0.14949959, 0.10657989, 0.15678029],
       [0.65475878, 0.61112632, 0.15130359, 0.38630224, 0.59134643],
       [0.02365568, 0.71765256, 0.71027491, 0.46577372, 0.33993732],
       [0.69644506, 0.98375941, 0.74706062, 0.96758019, 0.59446233]])

In [39]:
matrix = arr.reshape((5,5))

In [40]:
matrix

array([[0.88142763, 0.13055543, 0.21486116, 0.22138729, 0.69008903],
       [0.9662225 , 0.73637454, 0.14949959, 0.10657989, 0.15678029],
       [0.65475878, 0.61112632, 0.15130359, 0.38630224, 0.59134643],
       [0.02365568, 0.71765256, 0.71027491, 0.46577372, 0.33993732],
       [0.69644506, 0.98375941, 0.74706062, 0.96758019, 0.59446233]])

In [41]:
matrix.max()

0.9837594078016034

In [42]:
matrix.min()

0.023655677409266218

In [46]:
# posicao do maior
matrix.argmax()

21

In [48]:
# posicao do menor
matrix.argmin()

15